### ISSUE TITLE
Why LGPL v3?

### ISSUE THREAD

**Issue by tewarid** [ExM/OncRpc#1]
Any particular reason to pick LGPL v3? I'm searching for an open source RPC library for .NET and your's is the only one I found, but your choice of license will make it difficult to adopt it in open source projects licensed under more liberal licenses (most these days).

**Comment by ExM** [comment]
This is a prototype. For real use, the code should be modified.
The GPL gives me a better chance of getting your changes back into my repo.

But the GPL does not exclude the use of proprietary solutions. In .Net, dynamic load of assemblies.

**Comment by tewarid** [comment]
Thank you.
